Time::DATE_FORMATS[:fechahora] = '%d/%b./%Y ~ %I:%M%p'
Time::DATE_FORMATS[:fechahoramil] = '%d/%b./%Y ~ %H:%M'
Date::DATE_FORMATS[:fecha] = '%d/%m/%Y'
Date::DATE_FORMATS[:dia_mes] = '%d/%b. %H:%M'
Time::DATE_FORMATS[:hora] = '%H:%M'