require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArribosBauxitasController do

  # This should return the minimal set of attributes required to create a valid
  # ArriboBauxita. As you add validations to ArriboBauxita, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArribosBauxitasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all arribos_bauxitas as @arribos_bauxitas" do
      arribo_bauxita = ArriboBauxita.create! valid_attributes
      get :index, {}, valid_session
      assigns(:arribos_bauxitas).should eq([arribo_bauxita])
    end
  end

  describe "GET show" do
    it "assigns the requested arribo_bauxita as @arribo_bauxita" do
      arribo_bauxita = ArriboBauxita.create! valid_attributes
      get :show, {:id => arribo_bauxita.to_param}, valid_session
      assigns(:arribo_bauxita).should eq(arribo_bauxita)
    end
  end

  describe "GET new" do
    it "assigns a new arribo_bauxita as @arribo_bauxita" do
      get :new, {}, valid_session
      assigns(:arribo_bauxita).should be_a_new(ArriboBauxita)
    end
  end

  describe "GET edit" do
    it "assigns the requested arribo_bauxita as @arribo_bauxita" do
      arribo_bauxita = ArriboBauxita.create! valid_attributes
      get :edit, {:id => arribo_bauxita.to_param}, valid_session
      assigns(:arribo_bauxita).should eq(arribo_bauxita)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ArriboBauxita" do
        expect {
          post :create, {:arribo_bauxita => valid_attributes}, valid_session
        }.to change(ArriboBauxita, :count).by(1)
      end

      it "assigns a newly created arribo_bauxita as @arribo_bauxita" do
        post :create, {:arribo_bauxita => valid_attributes}, valid_session
        assigns(:arribo_bauxita).should be_a(ArriboBauxita)
        assigns(:arribo_bauxita).should be_persisted
      end

      it "redirects to the created arribo_bauxita" do
        post :create, {:arribo_bauxita => valid_attributes}, valid_session
        response.should redirect_to(ArriboBauxita.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved arribo_bauxita as @arribo_bauxita" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArriboBauxita.any_instance.stub(:save).and_return(false)
        post :create, {:arribo_bauxita => {}}, valid_session
        assigns(:arribo_bauxita).should be_a_new(ArriboBauxita)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ArriboBauxita.any_instance.stub(:save).and_return(false)
        post :create, {:arribo_bauxita => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested arribo_bauxita" do
        arribo_bauxita = ArriboBauxita.create! valid_attributes
        # Assuming there are no other arribos_bauxitas in the database, this
        # specifies that the ArriboBauxita created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ArriboBauxita.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => arribo_bauxita.to_param, :arribo_bauxita => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested arribo_bauxita as @arribo_bauxita" do
        arribo_bauxita = ArriboBauxita.create! valid_attributes
        put :update, {:id => arribo_bauxita.to_param, :arribo_bauxita => valid_attributes}, valid_session
        assigns(:arribo_bauxita).should eq(arribo_bauxita)
      end

      it "redirects to the arribo_bauxita" do
        arribo_bauxita = ArriboBauxita.create! valid_attributes
        put :update, {:id => arribo_bauxita.to_param, :arribo_bauxita => valid_attributes}, valid_session
        response.should redirect_to(arribo_bauxita)
      end
    end

    describe "with invalid params" do
      it "assigns the arribo_bauxita as @arribo_bauxita" do
        arribo_bauxita = ArriboBauxita.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArriboBauxita.any_instance.stub(:save).and_return(false)
        put :update, {:id => arribo_bauxita.to_param, :arribo_bauxita => {}}, valid_session
        assigns(:arribo_bauxita).should eq(arribo_bauxita)
      end

      it "re-renders the 'edit' template" do
        arribo_bauxita = ArriboBauxita.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ArriboBauxita.any_instance.stub(:save).and_return(false)
        put :update, {:id => arribo_bauxita.to_param, :arribo_bauxita => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested arribo_bauxita" do
      arribo_bauxita = ArriboBauxita.create! valid_attributes
      expect {
        delete :destroy, {:id => arribo_bauxita.to_param}, valid_session
      }.to change(ArriboBauxita, :count).by(-1)
    end

    it "redirects to the arribos_bauxitas list" do
      arribo_bauxita = ArriboBauxita.create! valid_attributes
      delete :destroy, {:id => arribo_bauxita.to_param}, valid_session
      response.should redirect_to(arribos_bauxitas_url)
    end
  end

end
